version: 2.1

jobs:
  build:
    docker:
      - image: "cimg/python:3.8"
    steps:
      - checkout
      - run: python main.py
  test:
    docker:
      - image: "cimg/python:3.8"
    steps:
      - checkout
      - run: python main-test.py
  
  deploy:
    docker:
      - image: "cimg/python:3.8"
    steps:
      - run: echo "Deploying..."
workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build 
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
          #   - test
          # filters:
          #   branches:
          #     only: main
            - hold
